<?php
/* 
 * @category  Event Manager Module
 * @package   ITwebexperts_Events

 * @license   http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      N/A 
 */
?>
<?php $_eventsItem = $this->helper('itwebexperts_events')->getEventsItemInstance(); ?>
<div id="events_item_messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-title">
    <h1><?php echo $this->escapeHtml($_eventsItem->getTitle()) ?></h1>

    <div class="events_item_subtitle">

    </div>
	
</div>

<div class="events_item_view">
    <?php if ($imageUrl = $this->getImageUrl($_eventsItem, 400)): ?>
       <p><img src="<?php echo $imageUrl ?>" alt="<?php echo $this->escapeHtml($_eventsItem->getTitle()) ?>" /></p>
    <?php endif; ?>
    <div class="events_item_content"><span style="font-size:14px;font-weight:bold">Event Details</span><br/><?php echo $_eventsItem->getDetails(); ?></div>

    <div class="pager">
        <a href="<?php echo $this->getBackUrl() ?>">
            <?php echo Mage::helper('itwebexperts_events')->__('Return to list') ?>
        </a>
    </div>
</div>
